### ISSUE TITLE
Python library LD2410: Error returning values?

### ISSUE THREAD

**Issue by fernajuf** [vjsyong/LD2410#2]
Thanks for the library. In my first attempts to understand how it works, I do tests that consist of repeatedly requesting the same information. The result is that every time I request the firmware version, the software returns a different value.
For example:
>>> print(radar.read_firmware_version())
INFO:root:Reading firmware version
V55.126.03031407
>>> print(radar.read_firmware_version())
INFO:root:Reading firmware version
V7.55.05030314
>>> print(radar.read_firmware_version())
INFO:root:Reading firmware version
V5.03.40048040

The same thing happens when I ask it to return the detection parameters:
>>> radar.edit_detection_params(2, 3, 1)
INFO:root:Editing detection parameters
>>> print(radar.read_detection_params())
INFO:root:Reading detection parameters
([148, 66, 112], [206, 10, 116, 200, 255, 55, 7, 20], [3, 5, 0, 0, 2, 148, 66, 206])
>>> print(radar.read_detection_params())
INFO:root:Reading detection parameters
([9, 192, 18], [180, 18, 199, 200, 255, 55, 7, 20], [67, 43, 0, 14, 33, 132, 18, 192])
>>> print(radar.read_detection_params())
INFO:root:Reading detection parameters
([130, 32, 203], [2, 38, 77, 134, 4, 126, 55, 7], [3, 3, 5, 64, 40, 128, 0, 8])

And the same, for example, when I ask for the Bluetooth MAC:
>>> radar.bt_enable()
INFO:root:Enabling Bluetooth
>>> radar.bt_query_mac()
INFO:root:Getting Bluetooth Address
'02:7d:00:00:7d:00'
>>> radar.restart_module()
INFO:root:Restarting module
>>> radar.bt_query_mac()
INFO:root:Getting Bluetooth Address
'00:02:yy:00:00:00'
>>> radar.restart_module()
INFO:root:Restarting module
>>> radar.bt_enable()
INFO:root:Enabling Bluetooth
>>> radar.bt_query_mac()
INFO:root:Getting Bluetooth Address
'00:00:00:00:55:00'

I am sure that I am not fully understanding how the LD2410 library for Python works.

I would appreciate some help.

**Comment by vjsyong** [comment]
It's been a while since I've used my own library so I might not be too familiar at this point. It seems that it could be a baud rate mismatch. Thus the values that come out might fluctuate depending on the run.
